CREATE TABLE DOCUMENT (
  id INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  chemin  VARCHAR(255) NOT NULL UNIQUE,
  extension  VARCHAR(255) NOT NULL,
  taille FLOAT NOT NULL,

  PRIMARY KEY (id)
);

CREATE TABLE MOT (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contenu VARCHAR(100) NOT NULL UNIQUE    
);

CREATE TABLE INDEXATION (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    document INT NOT NULL,
    mot INT NOT NULL,
    frequence_mot INT NOT NULL, 

    FOREIGN KEY (document) REFERENCES DOCUMENT(id),
    FOREIGN KEY (mot) REFERENCES MOT(id)

);