CREATE TABLE DOCUMENT (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL UNIQUE    
);

CREATE TABLE MOT (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contenu VARCHAR(100) NOT NULL UNIQUE    
);

CREATE TABLE INDEXATION (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    document INT NOT NULL,
    mot INT NOT NULL,
    frequence_mot INT NOT NULL, 

    FOREIGN KEY (document) REFERENCES DOCUMENT(id),
    FOREIGN KEY (mot) REFERENCES MOT(id)

);